repository: timeseriesAI/tsai
output: web
topnav_title: tsai
site_title: tsai
company_name: timeseriesAI
description: Practical Deep Learning for Time Series / Sequential Data library based on fastai & Pytorch
google_search: 11230dd821e5ae508
use_math: true
google_analytics: 
twitter_username: timeseriesAI

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor
 
exclude: [vendor]

default_badges:
  colab: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars:
- home_sidebar

plugins:
    - jekyll-remote-theme
    
remote_theme: fastai/nbdev-jekyll-theme
baseurl: /